django_lottery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import static
from django.conf import settings

urlpatterns = [
	#path('lottery/', include('lottery.urls')),
    path('', include('lottery.urls')),
    path('admin/', admin.site.urls),
]


urlpatterns += static.static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lottery/urls.py
from django.urls import path

from . import views

app_name = 'lottery'
urlpatterns = [
    path('', views.index, name='index'),
    path('import/', views.simple_upload, name='import'),
    path('<int:award_id>/reset/', views.resetAward, name='reset'),
    path('<int:award_id>/doLottery/', views.doLottery, name='doLottery'),
    path('reload/', views.reloadPage, name='reload'),
]

lottery/models.py
from django.db import models

# Create your models here.


class Award(models.Model):
	award_id = models.IntegerField(primary_key=True) 
	first_selection = models.IntegerField(default=1)
	is_done= models.BooleanField(default=False)
	award_name =models.CharField(max_length=20,blank=True)
	descript_text = models.CharField(max_length=50,blank=True)
	award_content = models.CharField(max_length=50,blank=True)
	award_group_id = models.IntegerField(default=1)
	award_amount = models.IntegerField(default=1)

class Person(models.Model):
	person_id = models.IntegerField(primary_key=True,default=0)
	employee_id = models.CharField(max_length=40,default="",blank=True)
	company = models.CharField(max_length=20,default="",blank=True)
	name = models.CharField(max_length=20)
	department = models.CharField(max_length=50,default="",blank=True)
	seniority = models.IntegerField(default=1)
	is_attend =models.BooleanField(default=True)
	award = models.ManyToManyField(Award,blank=True)
	#create_date = models.DateTimeField('date created')
	def __str__(self):
		return self.name

lottery/views.py
from django.shortcuts import render
from django.template import loader
from django.urls import reverse

from .models import Person, Award
# Create your views here.

from django.http import HttpResponse,HttpResponseRedirect
from django.http import JsonResponse

import random
import json

from tablib import Dataset
from import_export import resources

from django.core import serializers

# not available
def simple_upload(request):
    if request.method == 'POST':
        person_resource = resources.modelresource_factory(model=Person)()
        dataset = Dataset()
        new_persons = request.FILES['myfile']

        imported_data = dataset.load(new_persons.read())
        result = person_resource.import_data(dataset, dry_run=True)  # Test the data import

        if not result.has_errors():
            person_resource.import_data(dataset, dry_run=False)  # Actually import now

    return render(request, 'lottery/import.html')


def index(request):
	award_list = Award.objects.exclude(award_id=0)
	awards_not_done = Award.objects.filter(is_done=False)
	current_award = None
	if (awards_not_done):
		current_award = awards_not_done.last()
	
	person_list = Person.objects.filter(award=None)
	

	

	context = {
		'award_list': award_list,
		'person_list': person_list,
		'current_award': current_award,
	}
	
	return render(request, 'lottery/index.html', context)

def resetAward(request,award_id):
	current_award = Award.objects.get(award_id=award_id)
	current_award.is_done = False

	end= len(current_award.person_set.all())
	start = end -current_award.first_selection
	
	last_added_person_set = current_award.person_set.all()[start:end]
	for p in last_added_person_set:
		current_award.person_set.remove(p)


	current_award.save()
	return HttpResponseRedirect(reverse('lottery:index'))

def reloadPage(request):
	return HttpResponseRedirect(reverse('lottery:index'))

def doLottery(request, award_id):

	current_award = Award.objects.get(award_id=award_id)
	
	if not current_award :
		return

	award_num_diff = (current_award.award_amount-len(current_award.person_set.all()))
	if award_num_diff < current_award.first_selection : 
		current_award.first_selection = award_num_diff
		print(current_award.first_selection)

	p_list_all = list(Person.objects.filter(award=None).filter(is_attend=True))
	p_list_first_select =[]


	
	random_list = random.sample(range(len(p_list_all)),min(len(p_list_all),current_award.first_selection))


	for i in random_list:
		p_list_first_select.append(p_list_all[i])

	for p in p_list_first_select:
		p.award.add(current_award)
		p.save()
	
	award_num_diff = (current_award.award_amount-len(current_award.person_set.all()))
	if(award_num_diff==0):
		current_award.is_done = True

	current_award.save()

	end = len(current_award.person_set.all())
	start = end - current_award.first_selection
	
	serialized_qs = serializers.serialize('json', current_award.person_set.all()[start:end])
	data = { "queryset" : serialized_qs}
	return JsonResponse(data)
	#return HttpResponseRedirect(reverse('lottery:index'))

lottery/templates/lottery/import.html
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>

lottery/templates/lottery/index.html
{% load static %}
<!DOCTYPE html>
<html>
<link rel="stylesheet" type="text/css" href="{% static 'lottery/style.css' %}">
<!--<link rel="stylesheet" type="text/css" href="{% static 'lottery/lottery.css' %}">-->
<head>
<title>Lottery</title>
<script src="{% static 'lottery/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'lottery/dial.js' %}"></script>
</head>
<body>
    <div id="sitebackground">
    <div id="sitebody">

        <div class="sidebar" id="sidebar_left">
            
            {% if award_list %}
                <ul>
                    <!--
                {% for a in award_list|dictsort:"award_id" %}
                    {% if a.award_id <= 17 %}
                        {% if current_award and a.award_id == current_award.award_id  %}
                        <li class="current" data-position="{{ a.award_id }}">{{ a.award_name }}</li>
                        {% else %}
                        <li data-position="{{ a.award_id }}">{{ a.award_name }}</li>
                        {% endif %}
                    {% endif %}
                {% endfor %}-->
                </ul>
            {% else %}
                <p>No awards are available.</p>
            {% endif %}
            <a href="javascript:;" class="btn" id="resultbtn" onclick="PopAllWinner()">得獎名單</a>
        </div>
        
        <div id="content">
            <div id="award_content">
                
                
            </div>
            <div id="award_remain">
                剩餘獎品數<br>
            </div>
            <div class="m-ui-dial" >
                    <div class="spinner_outer">
                        <div class="spinner" id="js_pointer" ></div>
                    </div>
                    <div class="pointer">
                        <div class="btn" >
                            {% if current_award %}
                            <div id="start_spinner" href="javascript:;" onclick="lottery.draw()" style="display: block">start</div>
                            {% endif %}
                        </div>



                    </div>
            </div>
            <!--
            {% if current_award %}
            <form action="{% url 'lottery:doLottery' current_award.award_id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Spin!">
            </form>
            {% endif %}
             -->
        


         
         </div>
    </div>
    </div>
    <div class="popWindow_wrap">
    <div class="popWindow" id="congrat" style="display: none">
                <p id="h1">{{current_award.descript_text}}</p>
                <p id="h2"></p>
                

             <div id="wontable">

                <div id="wontable_row">

                </div>
                 

                 </div>
            <div id="confirmbtn_set_wrap">
                 <div id="confirmbtn_set">
                    <a class="confirmbtn" href="javascript:;" onclick="ResetAward()">重抽</a>
                    <a class="confirmbtn" href="javascript:;" onclick="CloseWinner()">確認</a>

                 </div>
             </div>

         </div>

         <div class="popWindow" id="all_won" style="display: none;">
             
             
             
            <div class="award_page">
                {% if award_list %}
                <div style="display:flex;font-size: 2em;font-weight: bold; line-height: 2em; width:100%;justify-content: center;">得獎名單</div>
                
            {% else %}
                <p>No awards are available.</p>
            {% endif %}


             
             </div>
             <a class="confirmbtn" href="javascript:;" onclick="CloseWinner()">Ｘ</a>
         </div>
         <div id="blackscreen" style="display: none">   </div>
         

    </div>



</body>
<script>

        var lottery = new LotteryDial(document.getElementById('js_pointer'), { // eslint-disable-line
          speed: 20, // 每帧速度
          areaNumber: 2 // 奖区数量
        })

        var index = -1
        var test,test_obj
        lottery.on('start', function () {
           //index = Math.round(Math.random() * $('ul#person_list li').length)
          //console.log( $('ul#person_list  li').length)
          lottery.setResult(index)
          SendAJAX()
      //    // 假如请求出错
      //    setTimeout(function () {
      //      lottery.reset()
      //    }, 1000)
        })
        lottery.on('end', function () {
            //AJAX Get result
            
            //PopWinner(test_obj)
        })

        var award_length = {{ award_list|length }}
       
        
        ShowAwardList()
        ShowRemains()
        ShowAwardContent()

        function SendAJAX()
        {
            $.ajax({
                type: "GET",
                {% if current_award %}
                url: "{% url 'lottery:doLottery' current_award.award_id %}",
                {% endif %}
                //data: data,
                success: function(data) {
                    test='{ "person" :'+ data.queryset +'}'
                    test_obj = JSON.parse(test)
                    setTimeout(function(){
                        PopWinner(test_obj)
                    },2000)
                    
                },

                error: function(response, error) {
                    alert(error)
                }
            })

        }
        //show award list 
        function ShowAwardList()
        {
            prev_award_group_id=0;
            {% if award_list %}
                {% for a in award_list|dictsort:"award_id" %}
                if(  {{a.award_group_id }} -prev_award_group_id >0)
                {
                    {% if current_award and a.award_group_id == current_award.award_group_id  %}

                    $("<li class=\"current\" data-position=\"{{ a.award_group_id }}\">{{ a.award_name }}</li>").appendTo("#sidebar_left ul")
                    {% else %}
                    
                    $("<li data-position=\"{{ a.award_group_id }}\">{{ a.award_name }}</li>").appendTo("#sidebar_left ul")
                    {% endif %}
                    prev_award_group_id = {{a.award_group_id }}
                }
                {% endfor %}
            {% endif %}
        }
        function ShowAwardContent()
        {
            var str = "{{current_award.award_content}}".split('#')
            var content =""
            if(str.length>=2)
                content = str[0]+"<br>"+str[1]
            else
                content = str[0]

            $("<span>"+content+"</span>").appendTo("#award_content")
        }

        function ShowRemains()
        {
            var remains = {{current_award.award_amount}} - {{current_award.person_set.all|length }}
            $("<span>"+remains+"</span>").appendTo("#award_remain")
        }

        function ShowDiv()
        {
            $("#congrat").css("display","none")
            $("#all_won").css("display","none")
            $("#blackscreen").css("display","none")
            $(".popWindow_wrap").css("display","none")
            //$("#sidebar_left").css("display","flex")
            //$("#resultbtn").css("display","block")

        }
        function HideDiv()
        {
            //$("#resultbtn").css("display","none")
            //$("#sidebar_left").css("display","none")
            //$("#sidebar_right").css("display","none")
            $(".popWindow_wrap").css("display","flex")
            $("#blackscreen").css("display","block")
                    
        }
        function PopWinner(person_list_obj)
        {
            HideDiv()
            $("#congrat").css("display","block")
            $("#wontable_row").empty()
            $("#congrat p:last").empty()

            var str = "{{current_award.award_content}}".split('#')
            var content =""
            if(str.length>=2)
                content = str[0]+str[1]
            else
                content = str[0]

            $("<span>{{current_award.award_name}}<br><br>"+content+"</span>").appendTo("#congrat p:last")

            for (var i = 0; i < person_list_obj.person.length; i++) {
                $("<div class=winner>"
                    +"<p id='winner_name'>"+person_list_obj.person[i]["fields"]["name"]+"</p>"
                    +person_list_obj.person[i]["fields"]["company"]+"<br>"
                    +person_list_obj.person[i]["fields"]["employee_id"]+"<br>"
                    +person_list_obj.person[i]["fields"]["department"]
                    +"</div>").appendTo("#wontable_row")
            }
            //centerHandler (); /*呼叫置中函式，使廣告區塊置中*/
        }

        function CloseWinner()
        {
            location.reload(false)
            ShowDiv()
        }

        function ResetAward()
        {
            $.ajax({
                type: "GET",
                {% if current_award %}
                url: "{% url 'lottery:reset' current_award.award_id %}",
                {% endif %}
                //data: data,
                success: function(data) {
                    ShowDiv()
                },

                error: function(response, error) {
                    alert(error)
                }
            })
        }

        function PopAllWinner()
        {
            HideDiv()
            $("#all_won").css("display","flex")
            award_length = {{ award_list|length }}
            var element_per_row = Math.ceil((award_length-1)/3)
            var row_count=0;


            
            {% for a in award_list|dictsortreversed:"award_id" %}

                var str = "{{a.award_content}}".split('#')
                var content =""
                if(str.length>=2)
                    content = str[0]+str[1]
                else
                    content = str[0]

                $("<div class=award_name_content>{{a.award_name}}-"+content+"  {{a.award_amount}}名</div>").appendTo(".award_page")
                $("<div class=award_winners_table></div>").appendTo(".award_page")
                {% for p in a.person_set.all %}
                    var forcount = {{forloop.counter}}
                    if(forcount%2==0)
                    {
                        $("<div class=award_winner id=even>{{p.name}}<br>{{p.company}}<br>{{p.employee_id}}<br></div>").appendTo(".award_winners_table:last")
                    }
                    else
                    {
                        $("<div class=award_winner id=odd>{{p.name}}<br>{{p.company}}<br>{{p.employee_id}}<br></div>").appendTo(".award_winners_table:last")
                    }
                    
                    
                {% empty %}
                    $("<div class=award_winner>尚未開獎</div>").appendTo(".award_page")
                {% endfor %}
                
            {% endfor %}
            //other list
        }
        function centerHandler(){/*設定置中的函式*/
            var scrollDist=$(window).scrollTop();/*取得捲動長度*/
            var myTop=($(window).height()-$("#popWindow").height())/2+scrollDist;
            /*取得垂直中央位置*/
            var myLeft=($(window).width()-$("#popWindow").width())/2;
            /*取得水平中央位置*/
            $("#popWindow").offset({top:myTop,left:myLeft});
            /*設定區塊於水平與垂直置中*/
        }


</script>
</html>